## 7.5文本数据处理

![image.png](./image21.png)

In [1]:
import jieba

raw_text = """
我爱上海
她喜欢北京
他在杭州工作
"""
stoplist=[' ','\n']

# 利用 jieba 进行分词
words = list(jieba.cut(raw_text))
# 过滤停用词，如空格，回车符\n等
words=[i for i in words if i not in stoplist]

#去重，然后对每个词加上索引或给一个整数
word_to_ix = { i: word for i, word in enumerate(set(words))}

Building prefix dict from the default dictionary ...
Dumping model to file cache /var/folders/jm/g284dt7s285942ndw76zxfk40000gp/T/jieba.cache
Loading model cost 1.500 seconds.
Prefix dict has been built successfully.


In [3]:
words

['我', '爱', '上海', '她', '喜欢', '北京', '他', '在', '杭州', '工作']

In [2]:
word_to_ix

{0: '我',
 1: '在',
 2: '爱',
 3: '他',
 4: '北京',
 5: '杭州',
 6: '工作',
 7: '喜欢',
 8: '上海',
 9: '她'}

In [5]:
from torch import nn
import torch

embeds = nn.Embedding(10, 8)

lists=[]

for k,v in word_to_ix.items():
    tensor_value = torch.tensor(k)
    embed = embeds(tensor_value)
    lists.append(embed.data)



In [6]:
lists

[tensor([-0.4637, -0.5688, -1.8339,  2.2226, -1.5609,  0.3559,  0.2312,  0.3042]),
 tensor([ 1.6484,  1.5183, -0.1050,  2.1923, -1.1768,  0.4110, -1.2634,  0.9915]),
 tensor([ 1.0855, -0.6416,  1.4958,  0.9437, -1.5849, -2.5311,  0.9916,  0.0361]),
 tensor([-0.0609, -0.8797, -1.2194, -1.4141,  0.3167,  0.5212, -1.1245, -0.5457]),
 tensor([-1.1675, -0.1503,  0.7919, -1.4970, -2.1399,  1.3304, -0.1488, -0.6035]),
 tensor([ 0.2530, -0.1693, -1.5616,  0.4834, -0.4340,  0.6901,  0.5365,  1.6437]),
 tensor([-0.2538,  1.5953,  0.4940,  0.2845, -0.5527, -1.3952,  0.2089,  0.4951]),
 tensor([ 0.4581, -1.0175,  0.0437, -0.8479,  1.2931,  0.5076, -0.3192, -0.4572]),
 tensor([ 2.2715, -0.4882, -1.0055, -0.1919, -0.2046,  0.2102, -1.3330,  0.4428]),
 tensor([-1.1646, -2.0563,  0.8385,  1.3934,  2.4068, -0.5239, -0.6420, -1.4901])]

In [7]:
word_to_ix = { "我": 0,  "喜欢": 1, "她": 2}
embeds = nn.Embedding(3, 5) # 3 words in vocab, 5 dimensional embeddings

ix = word_to_ix["我"] 
lookup_tensor = torch.LongTensor([ix])
me_embed = embeds(lookup_tensor)

In [8]:
ix

0

In [9]:
lookup_tensor

tensor([0])

In [10]:
me_embed

tensor([[ 0.9674, -0.3753,  0.5218, -0.3350,  0.4684]],
       grad_fn=<EmbeddingBackward0>)