In [1]:
import torch

In [2]:
# 定义马尔可夫链的状态空间和转移概率矩阵
states = ['Sunny', 'Rainy']
transition_probabilities = torch.tensor([[0.8, 0.2],  # Sunny -> Sunny, Sunny -> Rainy
                                         [0.4, 0.6]]) # Rainy -> Sunny, Rainy -> Rainy

# 生成观测数据
observations = ['Sunny', 'Sunny', 'Rainy', 'Rainy', 'Sunny']

# 初始化转移概率矩阵的估计
estimated_transition_probabilities = torch.rand(2, 2, requires_grad=True)

# 定义优化器
optimizer = torch.optim.Adam([estimated_transition_probabilities], lr=0.1)

# 进行估计
num_epochs = 1000
for epoch in range(num_epochs):
    # 计算似然函数
    log_likelihood = 0
    for i in range(len(observations) - 1):
        current_state_index = states.index(observations[i])
        next_state_index = states.index(observations[i + 1])
        log_likelihood += torch.log(estimated_transition_probabilities[current_state_index, next_state_index])
    
    # 最大化似然函数等价于最小化负的似然函数
    loss = -log_likelihood
    
    # 梯度清零
    optimizer.zero_grad()
    
    # 反向传播
    loss.backward()
    
    # 更新参数
    optimizer.step()
    
    # 打印当前的损失值
    if (epoch + 1) % 100 == 0:
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item()}')

# 输出估计的转移概率矩阵
print("Estimated transition probabilities:")
print(estimated_transition_probabilities.detach().numpy())

f:\apps\miniconda3\envs\py310\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


Epoch [100/1000], Loss: -6.100152969360352
Epoch [200/1000], Loss: -7.934630393981934
Epoch [300/1000], Loss: -9.074251174926758
Epoch [400/1000], Loss: -9.908958435058594
Epoch [500/1000], Loss: -10.57122802734375
Epoch [600/1000], Loss: -11.122459411621094
Epoch [700/1000], Loss: -11.596203804016113
Epoch [800/1000], Loss: -12.012822151184082
Epoch [900/1000], Loss: -12.385605812072754
Epoch [1000/1000], Loss: -12.723711013793945
Estimated transition probabilities:
[[14.808398 24.238363]
 [27.68827  33.879196]]


In [3]:
estimated_transition_probabilities.detach()

tensor([[14.8084, 24.2384],
        [27.6883, 33.8792]])

In [4]:
estimated_transition_probabilities.detach().numpy()

array([[14.808398, 24.238363],
       [27.68827 , 33.879196]], dtype=float32)

: 